
name: tweetscraper

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "scrape"
  scrape:
    # runs on ubuntu cause  macos costs money and windows is for scrubs
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Signals run
      - name: scrape-init
        run: echo 'init scrape'

      # Installs dependencies
      - name: Install dependencies
        run: |
          pip install snscrape pandas
          
      - name: perform scrape
        run: |
          cd src
          python scrape.py
    

